### PR TITLE
Move leadership from broker to raft

### PR DESCRIPTION
**Pull request by shwetabhgarg**
Changes:
- moved leader.go from broker package to raft package to finish the separation between broker and raft

Next steps:
- add raft test (mock out serf)
- add broker tests (mock out serf and raft)
- modify server tests (mock out broker)

### CODE REVIEW

**Comment by travisjeffery** [comment]
looks pretty good, i'm just thinking about whether it makes sense to pass the serf event channel around (along with the serf instance in many cases) or just put a getter on the serf instance for the event channel

**Comment by shwetabhgarg** [comment]
My 50 cents: I like getters for reading data variables but not for fetching a channel, because with getters, often there is no good way of predicting/restricting a channel's consumers as the codebase grows. I prefer to explicitly pass channels around so that visibility of a channel is always restricted to rightful users. Possible exception would be a broadcasting/queueing channel that is open to all for adding events e.g. loggerChannel<- .

Nonetheless, would you like me to modify this PR and make a getter for the channel?

**Comment by shwetabhgarg** [comment]
Sorry, is the expression "my two cents"?

**Comment by travisjeffery** [comment]
yeah "my two cents" is the expression.

ok i'll take another look again this weekend and think about it

**Comment by travisjeffery** [comment]
btw the i added you as a collaborator - let's keep the workflow the same so keep making prs and i'll merge them. but you've been doing a lot of good stuff so you're more than a regular contributor.

**Pull request merged**
