### PR TITLE
Added few unit-tests for broker

### PR DESCRIPTION
**Pull request by Rushit**

### CODE REVIEW

**Comment by Rushit** [comment]
Hi @travisjeffery ,
Happy to contribute in any area. Just started with unit-tests so I can get familiar better with the codebase. Let me know if you want me to follow any plans to get more coverage in codebase.

**Comment by travisjeffery** [comment]
hey @Rushit thanks for the contribution. i would put these brokers tests in a separate file though called "broker_test.go". replicator_test.go should just test the replicator and replication.

**Comment by Rushit** [comment]
ok i'll separate them out.

**Comment by travisjeffery** [comment]
closing this, open a new pr, when you get a chance. thanks.

**Pull request closed without merging**
