### PR TITLE
broker tests #67

### PR DESCRIPTION
**Pull request by ryanstinson**
- Test broker: New()
  - Broker struct is initialized properly
  - Serf.Bootstrap is called correctly  
  - Raft.Bootstrap is called correctly    
  - Handle all error cases
- Test broker: Join()
   - Add test for serf error
 - Test broker: partition()
   - Add test for empty topic
 - Test broker: startReplica()
   - Add test for starting as leader
   - Add test for starting as follower
   - Add test for existing topic
   - Add test for duplicate partition
   - Add test for commitlog New() error

### CODE REVIEW

**Comment by travisjeffery** [comment]
I wrote some similar tests this weekend, can you update your PR, you've got some more error condition tests we can add. Thanks.

**Comment by ryanstinson** [comment]
Just saw the commit as I got the merge conflicts. I'll merge yours in and keep the new tests.

**Comment by travisjeffery** [comment]
@ryanstinson sounds good. I was going to hack on the tests because I feel like them lacking is holding back the development of everything else, but if you can push those forward in the next 2-3 days I'll wait.

I just pushed another change removing the individual/private handler tests because I want to test all those through the public Run api like the existing api versions handling is tested - so make sure you pull that before continuing. 

Can you push up your changes piecemeal, whenever you have something that works to look at, I just don't want to waste your time pushing up something I don't like/doesn't fit.

Thanks for the help!

**Comment by ryanstinson** [comment]
@travisjeffery I agree, my goal is to help you get broker tested 100% ASAP. I will pull your changes and submit small pieces at a time. Please give feedback regarding the tests for Broker New and don't hold back - I have a thick skin. The more feedback, the better my contributions will be going forward. Thanks.

**Comment by ryanstinson** [comment]
@travisjeffery merged our broker: test New() together. I made some changes to be able to use deep copy for comparing expected Broker to actual.

However, the joins_with_serf test is failing with nil ref so I'll take a look at that.

**Comment by ryanstinson** [comment]
@travisjeffery Regarding the individual private handlers for Broker, do you think those handlers should be pulled out as a separate func with a handler interface? That way they could also be independent and would reduce the Broker code.

**Comment by travisjeffery** [comment]
@ryanstinson the way they're setup is ok for now i think, there's isn't much the same between them as they are.

did you merge or rebase master? looks like no, i'd recommend doing that before continuing. or create a new branch off master and start fresh with your changes.

**Comment by ryanstinson** [comment]
@travisjeffery Yes, I am completely merged up to your latest commit. I just confirmed.

**Comment by ryanstinson** [comment]
@travisjeffery Can you merge this?

**Comment by travisjeffery** [comment]
Thanks @ryanstinson, merged. Checkout https://github.com/travisjeffery/jocko/commit/6553b9a237862cc6e839e0d2ab1efed883545933 for some fixes on the style, test names. The way you had them named were more topical, I want them named more for the reason the test is there, for instance if it's testing an error, instead of saying "new broker port error"/"broker port error" I want it to say "no broker port error"

**Comment by ryanstinson** [comment]
@travisjefferey Got it. I reviewed your changes and will follow that naming convention going forward.

**Pull request merged**
