### PR TITLE
Broker cleanup 2

### PR DESCRIPTION
**Pull request by shwetabhgarg**
Part 2 of Issue #22 
@travisjeffery Made the changes suggested in PR #25 

Change set: Added wrapper over serf.MemberStatus and raft.FSM to cleanly hide hashicorp raft and serf from jocko behind interfaces

Next steps: add/edit tests
Will open a new issue for this

### CODE REVIEW

**Comment by travisjeffery** [comment]
Don't make a separate issue, the PR is basically an issue with code.

**Comment by travisjeffery** [comment]
Looks pretty good!

**Comment by shwetabhgarg** [comment]
Cool. Please merge PR.

**Comment by travisjeffery** [comment]
ok merged it

**Pull request closed without merging**
