### PR TITLE
Refactor tests

### PR DESCRIPTION
**Pull request by shwetabhgarg**
Changes done:
- Moved tests to their own package
- Exposed type replicator, re-wrote replicator tests without internals (using mocks)
- Re-wrote serf tests without broker
- Minor code changes in commitlog and server: stop accepting connections after server shutdown

Next steps (TODO):
- Raft: move leader.go from broker to raft package to finish their separation, write tests for raft
- Broker: write tests for broker (mocking out serf/raft) to cover more cases
- Server: modify server tests by mocking out broker, add tests to cover remaining request/response cases

### CODE REVIEW

**Comment by shwetabhgarg** [comment]
Added a commit to this branch to fix a minor issue in a test file. CI build had passed for this PR earlier, but after the commit, CI build was triggered again and it failed for a different (non-related) test.
@travisjeffery Could you re-trigger the build to see if the issue persists?

**Comment by travisjeffery** [comment]
-1 on having all the tests in the same package. all the tests should be alongside the code they test. and if possible those can be in their own packages. e.g. the server package and server_test package how it was before.

the only top-level test dirs there should be are "testutil" and "mock" to include the mock types. So there'd be a file called mock/mock.go and it'd include a type called Proxy that's the Proxy mock.

**Comment by shwetabhgarg** [comment]
Cool. I'll move the tests back to their packages. Would you be okay with each package having its own test sub-directory e.g. _server_ package would have a sub-directory _tests_ (package "server/tests") containing the _server_test_ file, _broker_ package would have a sub-directory _tests_ (package "broker/tests") containing _broker_test_ and _replicator_test_ files, and so on?

**Comment by travisjeffery** [comment]
no keep them in the same directory /server/{server.go,server_test.go} I don't see many projects that have nested test directories. even in packages with lots of files it's easy to see the groups of files when they're sorted alphabetically.

**Comment by shwetabhgarg** [comment]
OK, moved tests back to code packages.

**Comment by travisjeffery** [comment]
merged thanks!

**Pull request closed without merging**
