### PR TITLE
Cleanup cluster example

### PR DESCRIPTION
**Pull request by sslavic**
While trying to reproduce https://github.com/travisjeffery/jocko/issues/20 I've noticed that:
- the cluster example is using outdated config flags - I found replacement for `log-dir` and `prometheus-addr` to be `data-dir` and `http-addr`, but I couldn't find replacement for `debug` so its usage is just removed (maybe `DevMode` is planned replacement, but that one is not configurable through CLI at the moment and it doesn't change zap logger so probably should be in separate commit)
- `broker-id` and `data-dir` config flags were configuring config struct properties which weren't actually used, there were duplicate struct properties which were used but not configurable throgh CLI
- `jocko` binary produced from both `make build` and by following cluster example is not gitignored so could be by accident committed to version control

This PR fixes the 3 mentioned issues in 3 separate commits.

### CODE REVIEW

**Comment by sslavic** [comment]
Looking into finding replacement for `serf-members`...

**Comment by sslavic** [comment]
`StartJoinAddrsLAN` is not being used at all. `DefaultLANSerfPort` is used for all and cannot be changed via CLI to be different per instance, so only one instance can start up on single host.

**Comment by winks** [comment]
I don't even get how the `make build` command can ever succeed when it tries to create a binary with the same name as a folder.
In the same way I don't think adding `jocko` to `.gitignore` when there's a folder named like that.

**Comment by MitchellJThomas** [comment]
Re: make build.  I ran into the same problem.  My un-informed suggestion is #106

**Comment by sslavic** [comment]
Closing this PR, @candlerb is covering this in his PRs.

**Pull request closed without merging**
